---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiskers
  namespace: webcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whiskers
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: whiskers
    spec:
      containers:
      - env:
        - name: BIND_ADDRESS
          value: 0.0.0.0:3000
        - name: CHAIN_API_URL
          value: https://webcat-sentry-1.freedom.press
        image: ghcr.io/freedomofpress/whiskers:v0.3.2
        imagePullPolicy: Always
        name: whiskers
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
